language: node_js
node_js:
  - "8.5"
cache:
  directories:
    "node_modules"

before_script:
  - npm run build:all
after_success:
  - npm run coveralls
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
